Repository opensheetmusicdisplay/opensheetmusicdisplay, pull requests merged in 2018-07, with the labels that each got.

#281 chore(package): update mocha to version 5.2.0
  package.json
Labels: dependencies

#279 chore(package): update @types/mocha to version 5.2.3
  package.json
Labels: dependencies

#270 Improvement/skyline
  .appveyor.yml
  .travis.yml
  demo/index.html
  demo/index.js
  external/vexflow/vexflow.d.ts
  karma.conf.js
  src/MusicalScore/Graphical/GraphicalInstantaniousDynamicExpression.ts
  src/MusicalScore/Graphical/GraphicalStaffEntry.ts
  src/MusicalScore/Graphical/MusicSheetCalculator.ts
  src/MusicalScore/Graphical/MusicSheetDrawer.ts
  src/MusicalScore/Graphical/SkyBottomLineCalculator.ts
  src/MusicalScore/Graphical/StaffLine.ts
  src/MusicalScore/Graphical/VexFlow/CanvasVexFlowBackend.ts
  src/MusicalScore/Graphical/VexFlow/SvgVexFlowBackend.ts
  src/MusicalScore/Graphical/VexFlow/VexFlowBackend.ts
  src/MusicalScore/Graphical/VexFlow/VexFlowInstantaniousDynamicExpression.ts
  src/MusicalScore/Graphical/VexFlow/VexFlowMusicSheetCalculator.ts
  src/MusicalScore/Graphical/VexFlow/VexFlowMusicSheetDrawer.ts
  src/MusicalScore/Graphical/VexFlow/VexFlowMusicSystem.ts
  src/MusicalScore/Graphical/VexFlow/VexFlowStaffEntry.ts
  src/OpenSheetMusicDisplay/OpenSheetMusicDisplay.ts
  test/Common/OSMD/OSMD_Test.ts
  test/Util/TestUtils.ts
Labels: refactoring

#278 chore(package): update webpack-dev-server to version 3.1.3
  package.json
Labels: dependencies

#265 Migration to loglevel for all logging statements
  src/MusicalScore/Graphical/BoundingBox.ts
  src/MusicalScore/Graphical/VexFlow/VexFlowStaffEntry.ts
  src/MusicalScore/VoiceData/SourceMeasure.ts
  src/OpenSheetMusicDisplay/OpenSheetMusicDisplay.ts
Labels: enhancement

#291 fix(MusicSheetCalculator.ts): shorten lyrics y offset
  src/MusicalScore/Graphical/MusicSheetCalculator.ts
Labels: bug, enhancement

#292 chore(package): update webpack to version 4.15.1
  package.json
Labels: dependencies

#305 Fix key signature without mode, common/alla breve time
  src/MusicalScore/Graphical/VexFlow/VexFlowConverter.ts
  src/MusicalScore/Graphical/VexFlow/VexFlowMusicSheetCalculator.ts
  src/MusicalScore/ScoreIO/InstrumentReader.ts
  test/MusicalScore/ScoreIO/Key_Test.ts
Labels: bug
